# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRScannerExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRScannerExample
pod 'C95-QR-Scanner-iOS', :git => 'https://github.com/Code95/C95-QR-Scanner-iOS.git', :tag => '1.0.2'


end
