# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRScannerExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRScannerExample
pod 'QRCodeScannerFramework', :git => 'https://github.com/husseinkishk/QRCodeScannerFramework.git', :tag => '1.0.2'

end
